language: node_js
node_js: node

sudo: false

script:
  - CI=false yarn build

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: ls.test.terminal.ink
  skip_cleanup: true
  edge:
    branch: v1.8.47
  on:
    branch: master

branches:
  only:
    - master
